name: clean_architecture
description: "A Flutter Clean Architecture Project by Hurkan Ugur :)."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Localization
    sdk: flutter

  font_awesome_flutter: ^10.7.0 # Application Icons
  flutter_riverpod: ^2.5.1 # State Management
  dio: ^5.4.3+1 # Http Client
  cookie_jar: ^4.0.8 # Cookie Management
  dio_cookie_manager: ^3.1.1 # Cookie Management
  shared_preferences: ^2.2.3 # Persisten Data Storage
  sqflite: ^2.3.3+1 # Local Data Storage
  equatable: ^2.0.5 # Object Comparison
  go_router: ^14.1.4 # Routing
  lottie: ^3.1.2 # Lottie Animations
  connectivity_plus: ^6.0.3 # Internet Connection
  encrypt: 5.0.1 # Encryption/Decryption
  crypto: ^3.0.3 # Hashing Algorithms
  path_provider: ^2.1.3 # Path Provider
  mime: ^1.0.5 # Mime Types For Downloading Files
  open_filex: ^4.4.0 # Opens Files
  image_picker: ^1.1.1 # Picks Images From Gallery
  file_picker: ^8.0.3 # Picks Files From Documents and Downloads
  permission_handler: ^11.3.1 # Permission Management
  device_info_plus: ^10.1.0 # Device Information

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/translations/
    - assets/certs/