name: clean_architecture
description: "A Flutter Clean Architecture Project by Hurkan Ugur :)."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Localization
    sdk: flutter

  cupertino_icons: ^1.0.6 # Application Icons
  flutter_riverpod: ^2.5.1 # State Management
  dio: ^5.4.2 # Http Client
  cookie_jar: ^4.0.8 # Cookie management
  dio_cookie_manager: ^3.1.1 # Cookie management
  shared_preferences: ^2.2.2 # Persisten Data Storage
  sqflite: ^2.3.2 # Local Data Storage
  equatable: ^2.0.5 # Object Comparison
  go_router: ^13.2.1 # Routing
  lottie: ^3.1.0 # Lottie Animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/translations/
    - assets/certs/